### ISSUE TITLE
Issues When i back to Previous 

### ISSUE THREAD

**Issue by ayaz56** [hakobvardanyan/NavigationComponentSample#1]
I have a fragment with a list that fills from server side. I call getDataFromServer on the onViewCreated method then, when a user clicks on an item, a new fragment shows.

The problem is that when I press the back button, onViewCreated is called again in my list fragment.

So, how can I prevent my first fragment from recreating again? I don't want unnecessary onViewCreated calls

**Comment by hakobvardanyan** [comment]
That is not related to this Navigation Component demo, I would say this is not an issue at all. 
The `onViewCreated` will be called even on menu fragments when you're changing tabs. I assume you're using a ViewModel with a fragment, that means before you start loading data from network you can check if the ViewModel already has latest data. If yes then show it, otherwise start loading.
